GET https://ique.vercel.app/api/stores/240
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJpcXVldWUiLCJpc3MiOiJ1bXMiLCJ1c2VyVHlwZSI6ImN1c3RvbWVyIiwiZXhwIjoxNjY3MzA2NDAzLCJpYXQiOjE2NjczMDEwMDMsInVzZXJJZCI6MjkyLCJqdGkiOiI3ZjViOTRmZC1kODY0LTQ5MDItYTE3Zi00NTdkZWFlNjIzZDUiLCJ1c2VybmFtZSI6Ind3eTcwMSJ9.pBalQGjoH3IePNkOdJUyvwAK6HSJvscDEmn5NAvIuG4