name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest
    strategy:
      matrix:
        swift:
          - 5.7
        platform:
          - iOS
        xcode:
          - ^14
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: mxcl/Xcodebuild
        uses: mxcl/xcodebuild@v1.11.0
        with:
          xcode: ${{ matrix.xcode }}
          platform: ${{ matrix.platform }}
          action: build # default = `test`
          code-coverage: true # default = `false`
          warnings-as-errors: true # default = `false`
          configuration: release # no default, ie. `xcodebuild` decides itself
